#!/bin/bash

set -e

export GO111MODULE=on 
# build webhook
CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o admission-webhook-example 
# build docker image
docker build --no-cache -t ccr.ccs.tencentyun.com/keyangxie/admission-webhook-example .
rm -rf admission-webhook-example

docker push ccr.ccs.tencentyun.com/keyangxie/admission-webhook-example
